### ISSUE TITLE
Add subscribe to newsletter section into collection page

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#12] opened 2021-05-12 14:46 UTC
![Screen Shot 2021-05-12 at 17 10 54](https://user-images.githubusercontent.com/4640135/117999323-04d33d00-b345-11eb-94da-013ab665dc3d.png)

## ❓Questions

- [x] What is the API that I need to use to implement this section?

**Comment by zdmitchell** [comment] 2021-05-12 16:59
> What is the API that I need to use to implement this section?

You probably want to use `/api/2.0/cart/newsletter/subscribe` with a body that looks like:
```
{
   "email": "test@example.com"
}
```

**Comment by dhmacs** [comment] 2021-05-12 17:20
@zdmitchell this probably is all I need to make the call, but do you also have documentation for the api?

Also:
- How do I test if everything is working? 
- How can I remove fake email that I'll add during testing?

**Comment by zdmitchell** [comment] 2021-05-12 18:55
> this probably is all I need to make the call, but do you also have documentation for the api?

Unfortunately we don't have docs for it, but that's the only param we accept.

> How do I test if everything is working?

A 200 response code should indicate that everything is working. We use that same endpoint on our Shopify stores, so if it isn't working we would now about it (I hope :smile:).

> How can I remove fake email that I'll add during testing?

We add these emails to our Active Campaign list. Just be sure to point the API at `www.cominor.com` when in development. Then it's no big deal if you add test emails.

This is where we call the same endpoint in our Shopify theme:
https://github.com/iFixit/shopify-v2/blob/1042deff6bfb37caa8b26f4f06e6c058acc7491e/src/scripts/layout/theme.js#L377-L394

**Comment by dhmacs** [comment] 2021-05-13 06:05
@zdmitchell so, the full url are:

- **Production**: https://ifixit.com/api/2.0/cart/newsletter/subscribe
- **Dev**: https://www.cominor.com/api/2.0/cart/newsletter/subscribe

right?

**Comment by zdmitchell** [comment] 2021-05-13 15:55
@dhmacs Yes that's correct.

**Comment by dhmacs** [comment] 2021-05-26 16:22
@sterlinghirsh (posting here for reference) I'm currently getting what it seems to be a CORS error when submitting requests to cominor API. Here's the link to test it: https://react-commerce-l5cjcrp0d-ifixit.vercel.app/collections/iphone-x

**Comment by dhmacs** [comment] 2021-05-31 17:57
@sterlinghirsh @zdmitchell do you have an update on this?

**Comment by zdmitchell** [comment] 2021-06-01 15:45
@dhmacs This is the code where we give CORS exemptions for Shopify:
```
if ((req.url ~ "^/api/2.0/user" || req.url ~ "^/api/2.0/store/user"
    || req.url ~ "^/api/2.0/cart/product/notifyWhenInStock")
    && (req.http.Origin == "https://ifixit-dev.myshopify.com"
    || req.http.Origin == "https://ifixit-test.myshopify.com"
    || req.http.Origin == "https://ifixit-eu-test.myshopify.com"
    || req.http.Origin == "http://localhost:3000")) {
      set resp.http.Access-Control-Allow-Credentials = "true";
   }
```
I can add an exemption for this, but I don't really understand that URL. Can it change?

**Comment by dhmacs** [comment] 2021-06-01 16:38
@zdmitchell It's not a big deal if it doesn't work on the preview url which is only temporary, but I'm having the same issue running on localhost (`http://localhost:3000`). 

Can you run this [branch](https://github.com/iFixit/react-commerce/tree/add-subscribe-to-newsletter-collection-section) on your machine and see if you have the CORS error too?

Also the snippet above does not seem to whitelist `/api/2.0/cart/newsletter/subscribe` or am I missing something?

**Comment by zdmitchell** [comment] 2021-06-01 16:50
> Also the snippet above does not seem to whitelist `/api/2.0/cart/newsletter/subscribe` or am I missing something?

Yeah exactly. I'm going to add it. I was just showing you why it doesn't work right now. I have a pull open on our main repo, and I'll let you know when it's merged.

**Comment by zdmitchell** [comment] 2021-06-01 21:47
It turns out that this wasn't a CORS issue at all. We returned a 422 if the request didn't come from a Shopify store because we didn't know which store to use for the "store" tag in Active Campaign. I overrode this behavior in dev to use the ifixit-dev store for requests from localhost, and confirmed that it works now.

**Comment by dhmacs** [comment] 2021-06-03 15:56
@zdmitchell does a 204 response mean that the API request has been successful? Is it expected the an empty response is returned?

**Comment by zdmitchell** [comment] 2021-06-03 15:57
> Does a 204 http status code response mean that the API request has been successful? Is it expected the an empty response is returned?

Yes to both. :smile:

**Closed** 2021-06-09 17:12 UTC
Labels: 0 feature
