### ISSUE TITLE
Firefox + DarkReader = slow collection pages

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1220] opened 2023-01-05 00:19 UTC
### Background
A user ran into the store pages freezing and [reported it on meta](https://meta.ifixit.com/Answers/View/17701/The+Bug+Folder:+Part+2+2022#answer18694).

Conditions: 
- Firefox version 108.0.1 (I tested on Windows)
- Adblock Plus
- DarkReader
- DuckDuckGo privacy plugin

### Sentry errors
- https://sentry.io/organizations/ifixit/issues/3854409468
- https://sentry.io/organizations/ifixit/issues/3854409549
- https://sentry.io/organizations/ifixit/issues/3828038597 (7.7k events/4k users)
- https://sentry.io/organizations/ifixit/issues/3828038608 (7.7k events/4k users)
- https://sentry.io/organizations/ifixit/issues/3851581332
- https://sentry.io/organizations/ifixit/issues/3851581334

### Repro
Click on pretty much anything. I did basic navigation with the product list collection buttons.

**Comment by erinemay** [comment] 2023-01-05 00:22
4 of them seem like they're affecting very few users, but https://sentry.io/organizations/ifixit/issues/3828038597 and
https://sentry.io/organizations/ifixit/issues/3828038608 have 7700 events with 4000 users.

**Comment by masonmcelvain** [comment] 2023-01-10 18:43
It's possible that those hydration Sentry errors are not related to this set of conditions, as we're seeing them across the board.

**Comment by masonmcelvain** [comment] 2023-01-18 15:25
The first 2 sentry events listed ([link1](https://sentry.io/organizations/ifixit/issues/3854409468) and [link2](https://sentry.io/organizations/ifixit/issues/3854409549)) might be related to this. The rest of them are hydration errors that are being addressed in #1209. Since the relevant events have only happened once (and I can't reproduce them), I don't think they are affecting many users.

The site seems to work fine with Adblock Plus and/or DuckDuckGo Privacy plugin installed. If DarkReader is installed (whether or not the others are installed), collection pages slow down so much that they are unusable.

I'd advise the user to disable DarkReader for ifixit.com, as I don't really think it's worth our time trying to fix this. If they are determined to get this fixed, they might consider [filing an issue with darkreader](https://github.com/darkreader/darkreader/issues).

**Comment by erinemay** [comment] 2023-01-18 16:32
cc: @AmberTaus

**Comment by masonmcelvain** [comment] 2023-01-19 20:50
Opened an issue with DarkReader: https://github.com/darkreader/darkreader/issues/10658

**Comment by masonmcelvain** [comment] 2023-01-20 18:31
I'm going to close this issue and if there's anything actionable on our end as a result of the DarkReader issue, I'll reopen this.

**Comment by masonmcelvain** [comment] 2023-01-20 18:31
Summary: This only happens on DarkReader Firefox, and it seems to happen for many other websites as well.

**Closed by masonmcelvain** 2023-01-20 18:31 UTC
Labels: 0 bug, research
