### ISSUE TITLE
Collections: 404 pages with back slash ("\") in the URL

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#713] opened 2022-09-19 15:48 UTC
I used our SEO tool, DeepCrawl, to crawl our Collections. One of the reports from the crawl is Non-200 Status Pages. It found 839 really odd URLs that I can't reproduce with a back slash in the URL. [Here's the full list of 839 pages it found](https://docs.google.com/spreadsheets/d/1jLpzQEyRshe3XW2I57GayoYz9JeZyb5UHyvNUiBlwIY/edit#gid=648564581), but for now, I think the best starting point is that somewhere in the crawl it found https://www.ifixit.com/Parts/MacBook_Air_13\" and https://www.ifixit.com/Parts/MacBook_Air_11\". Can we try to find in our database or something those URLs and where/how the crawler is finding them? And if we find it, can we fix it so we get rid of these unwanted 404s?

**Comment by ifixitmaxb** [comment] 2022-09-19 16:09
My only hunch is perhaps our JSON files that have backsplash being used as an escape character.

**Comment by ifixitmaxb** [comment] 2022-09-19 16:14
Potentially related so I'm going to put it here for now, but DeepCrawl also found 1,205 "malformed URLs" and they all have weird uses of backsplashes, in most cases a string of 7 backsplashes in a row. [I added a tab to the same sheet with the 1,205 "malformed URLs"](https://docs.google.com/spreadsheets/d/1jLpzQEyRshe3XW2I57GayoYz9JeZyb5UHyvNUiBlwIY/edit#gid=2003737554). For example, \"https://www.ifixit.com/Parts/iPad_Pro_12.9\\\\\\\"\" and \"https://www.ifixit.com/Parts/iMac_Intel_17\\\\\\\"\"

**Comment by federicobadini** [comment] 2023-07-05 08:38
Is this still actual?

**Comment by sterlinghirsh** [comment] 2023-07-05 22:31
@ifixitmaxb have you run a recent crawl?

**Comment by dhmacs** [comment] 2023-10-24 15:28
@ifixitmaxb I'm closing this. Feel free to re-open it if the issue is still present

**Closed as completed by dhmacs** 2023-10-24 15:28 UTC
