### ISSUE TITLE
Product Page: Add tests for a product with different variants

### ISSUE THREAD

**Issue by mlahargou** [iFixit/react-commerce#1044] opened 2022-11-18 17:56 UTC
- [ ] `Condition`
   - [ ] `Style`
   - [ ] `Color`
   - [ ] Ensure the price in the cart matches the price for specific condition/variant/color.

**Comment by batbattur** [comment] 2022-11-24 05:27
Added a new test for a product with different **`style`** variants in https://github.com/iFixit/react-commerce/pull/1062. 

Going to skip creating tests for the `Condition` and `Color`, since it's going to be essentially a duplicate of the #1062.

**Closed** 2022-11-27 14:57 UTC
Labels: QAE
