### ISSUE TITLE
Admins: Add the same links from the previous product page

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#941] opened 2022-10-28 17:10 UTC
[`admin-product-links`](https://github.com/iFixit/react-commerce/compare/admin-product-links)

PPv1 had useful links to internal tools at the top of the page that were only shown to admins (or employees?)

Do This
====

Add these links to the new product page someplace somehow:
https://github.com/iFixit/ifixit/blob/1507f4523ef22b5b452d1720694f3c5064a199c9/Cart/UI/templates/breadcrumbs.phtml#L3-L17

https://github.com/iFixit/ifixit/blob/1507f4523ef22b5b452d1720694f3c5064a199c9/Cart/Libs/ProductDisplayLib.php#L118-L127

Preferably, don't adjust the layout so employees still get the same look and feel.

CC @sterlinghirsh @jeffsnyder

**Comment by jeffsnyder** [comment] 2022-10-28 20:55
Semi-duplicate of https://github.com/iFixit/react-commerce/issues/416

**Comment by dhmacs** [comment] 2022-11-02 10:48
cc @mmarcon91

**Comment by mmarcon91** [comment] 2022-11-02 13:34
I designed a more generic bar, it is inspired by Shopify's UX for non-headless stores.
So it can be used in multiple contexts.

https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=1134%3A31139

**Comment by sterlinghirsh** [comment] 2022-11-08 19:34
Ideally we can implement this without having to pass special info, i.e. using redirectors on our php side or something.

**Comment by sterlinghirsh** [comment] 2022-11-15 17:26
I'd like to avoid having to add another bar to the page. I'm okay if this lives in a menu in the top. Could be the same bar with the breadcrumbs. Could be in the user menu if necessary, though that's a little hard to see, but maybe that's okay for the moment.

**Comment by mmarcon91** [comment] 2022-11-16 14:07
I'd like to avoid if possible to mix iFixit internal tooling with user facing features. It would waste screen real estate that we might need for other user facing features and it'll create a coupling between these two separate domains (i.e. changing something user related might involve changes to the admin tooling as well). 
The reason I'm proposing this is that it's completely independent from the UI, and allows have to evolve these two aspects separately. Please note that the bar is dismissible, so you won't have it around all the time if you don't want it.

**Comment by sterlinghirsh** [comment] 2022-11-16 18:11
I agree I don't want to mix them in a way where they're fighting for screen real estate, but putting it in a menu doesn't seem too obtrusive. I think we may need a menu anyway for all the options we'll want to add, whether that menu lives in a special bar or the existing user menu could go either way.

**Comment by danielbeardsley** [comment] 2022-11-16 18:49
I vote for moving the whole thing to a big "Links page" on our php app and only have one link in the react-commerce repo. I say this cause I'd could see us wanting many links and to conditionally show them based on a bunch of state not available to react-commerce.

**Comment by mmarcon91** [comment] 2022-11-17 10:35
> I agree I don't want to mix them in a way where they're fighting for screen real estate, but putting it in a menu doesn't seem too obtrusive. I think we may need a menu anyway for all the options we'll want to add, whether that menu lives in a special bar or the existing user menu could go either way.

Which direction do we want to go? 
If we want to use the current bar and insert other options it can be done. 

There is a component that already provides various options on the sub-navigation-bar : https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=127%3A14037&t=bQwXOMEnro4vO8D5-4

I could create a graphical separation between common user and admin

**Comment by sterlinghirsh** [comment] 2022-11-22 17:22
I don't see the value in the links page when we can put the links in a component on the current page. I'm still inclined to put the extra links in the user menu just to start out, and then we can move them if we want. That may end up meaning an admin bar, but I don't want to commit to that yet.

**Comment by sterlinghirsh** [comment] 2022-11-22 17:23
Actually, using the dropdown in the sub-nav bar is better. If that's available, let's start with that instead of the user menu.

**Comment by danielbeardsley** [comment] 2022-11-22 19:06
> I don't see the value in the links page when we can put the links in a component on the current page

Two reasons:

* There may be ~10-20 links (one for each shopify store, one for each shopify store admin interface, strapi, akeneo, view inventory, product errors, ...)
* It's really convenient to use a browser search-engine definition to make a shortcut to this page (which then has all the links)

**Comment by sterlinghirsh** [comment] 2022-11-22 20:54
I think the links to the other stores would be handled by the existing store switcher. It's not crazy for each store to have a similar admin link function that takes you to its own admin page, but I don't think there's much of a case for going US store to FR admin. So I think the ones I'm interested in are current store Shopify admin, Akeneo, Inventory. There's no strapi link per product, and while product errors may be relevant, there's also no per-product error dashboard, so we don't really need that either. A bookmark would work fine for that if you're visiting the error dashboard enough.

**Comment by danielbeardsley** [comment] 2022-11-22 21:15
> But I don't think there's much of a case for going US store to FR admin

I agree, which is why I was suggesting an *admin page*. i.e. I have a product code and I want to go to one of the pages relevant to this product. We've already created a few auto-redirectors in admin but discovering them is impossible.

If we had a canonical (and fast) admin page that had all relevant links about products we'd only need one link on a product page.

**Comment by jeffsnyder** [comment] 2022-11-28 19:54
Shortcut URLs are useful for power-users. My team uses them. I'm not sure everyone in Marketing, Shipping, CS, etc., use them. Linking to an admin page feels like an extra, unnecessary step. 

>  I don't think there's much of a case for going US store to FR admin.

Correct. We can rely on the Preferred Store selector.

**Comment by masonmcelvain** [comment] 2022-12-13 17:59
Did we ever reach an agreement on how to implement this? Is the [sub-navigation bar](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=118%3A12832) the plan?

**Comment by sterlinghirsh** [comment] 2022-12-13 18:45
Yes, if we have a component that can do it.

**Closed** 2022-12-17 21:09 UTC
