### ISSUE TITLE
Redirect /Tools/Sale to /Shop/Sale and vice-versa

### ISSUE THREAD

**Issue by masonmcelvain** [iFixit/react-commerce#1911] opened 2023-08-12 16:20 UTC
> We noticed that [ifixit.com/Tools/Sale](http://ifixit.com/Tools/Sale) and [ifixit.com/Shop/Sale](http://ifixit.com/Shop/Sale) both exist. The former canonicals to the latter. But we should probably redirect the former to the latter? Am I missing anything here? Do a lot of collections exist on either /Tools or /Parts that we are unaware of and that canonical to a /Shop version? Or is this just a weird one-off situation and we can just do a walrusmapp redirect?

> We have a single page built in Strapi. It looks like /Shop pages are also accessible via /Tools

> Got it. Then I think I'd like to fix this. I'd rather they redirect than canonical

Slack thread: https://ifixit.slack.com/archives/C02KMFEHX62/p1691797628050609

CC @ifixitmaxb

**Comment by sterlinghirsh** [comment] 2023-08-22 02:01
Make sure we don't just fix this one url. Any marketing productlist should canonical to /Shop/x and redirect if it's accessed from the /Tools/x url and vice versa.

**Comment by sterlinghirsh** [comment] 2023-08-25 20:48
We now redirect Tools to Shop, but I think it should do the same thing for Shop to Tools. e.g. /Shop/Toolkits should redirect to /Tools/Toolkits.

**Comment by masonmcelvain** [comment] 2023-08-25 21:07
Can you explain the motivation for redirecting /Shop/[handle] to /Tools/[handle]? Right now www.ifixit.com/Shop/Toolkits 404s and has no traffic in [datadog](https://app.datadoghq.com/logs?query=%40path%3A%22en-US%2FShop%2F%5Bhandle%5D%22%20%40proxy.path%3A%22%2FShop%2FToolkits%22%20&agg_q=%40proxy.path&cols=host%2Cservice&index=%2A&messageDisplay=inline&sort_m=&sort_t=&stream_sort=desc&top_n=10&top_o=top&viz=stream&x_missing=true&from_ts=1692996573981&to_ts=1692997473981&live=true) (except for my one 404ing request). AFAIK we've always 404'd non-marketing pages on the /Shops/[handle] route.

**Comment by sterlinghirsh** [comment] 2023-08-25 23:32
I was just doing it to be consistent and in case we ever wanted to switch a page from Tools to Shop. I don't have a specific case in mind. I'm not married to it but it seems like it's easy to set up and we could reuse the same code. If not or if nobody cares then whatever.

**Comment by dhmacs** [comment] 2023-10-24 14:34
I was looking into this to see if we can close this issue and I'm a little bit confused by the fix that has been deployed. Marketing product lists were not meant to be shown under `/Tools`, it was a bug, so why are we still allowing this to happen?

![image](https://github.com/iFixit/react-commerce/assets/4640135/e06f1d7d-fb02-4ffc-afec-adb36c67ce77)

cc @masonmcelvain @sterlinghirsh

**Comment by masonmcelvain** [comment] 2023-10-24 17:04
> Marketing product lists were not meant to be shown under /Tools, it was a bug, so why are we still allowing this to happen?

I agree with you that it feels wrong to show marketing pages under /Tools. This is almost the same question  I was asking here https://github.com/iFixit/react-commerce/issues/1911#issuecomment-1693930277.

> I'm a little bit confused by the fix that has been deployed

We saw traffic to `/Tools/Sale` in DataDog at one point, which led us to believe that our marketing team sent out an email with a link to that url. We're unsure if other emails were sent out with similar typos. We decided to redirect from `/Tools/*` to `/Shop/*` if appropriate, instead of 404ing `/Tools/Sale` which might cause us to lose conversions.

This issue is still open because @sterlinghirsh thinks the `case ProductListType.Marketing { ... }` code should have the same behavior as the current `case ProductListType.ToolsCategory { ... }` code. That is, we should redirect to the canonical url when a tools page is visited at a marketing url (e.g. `/Shop/Toolkits` should redirect to `/Tools/Toolkits`).

**Comment by dhmacs** [comment] 2023-10-24 17:34
> We're unsure if other emails were sent out with similar typos

Oh I see, that make sense. Imo the best option here is to make sure that no new email campaigns are sent using the wrong url and stop supporting marketing product lists under tools before this become set in stone due to too many backlinks.

**Comment by sterlinghirsh** [comment] 2023-10-24 20:25
> make sure that no new email campaigns are sent using the wrong url

I agree. I think having the url redirect rather than just working will help that though.

> and stop supporting marketing product lists under tools

Yeah I think we may be good to do that now. Not sure if there's a good way to check whether people are getting redirected but if it's down to 0 or close to it, we could drop the redirect.

**Comment by sterlinghirsh** [comment] 2023-10-24 20:25
And I'd also be okay with dropping the idea of redirecting the other way too.

**Comment by masonmcelvain** [comment] 2023-10-25 00:06
>  Not sure if there's a good way to check whether people are getting redirected

I tried looking this up in [Datadog](https://app.datadoghq.com/logs?query=service%3Areact-commerce-prod.vercel.app%20%40path%3A%22en-US%2FTools%2F%5Bhandle%5D%22%20%40statusCode%3A308%20%40proxy.path%3A%5C%2FTools%5C%2FSale%2A%20&cols=host&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&view=spans&viz=stream&from_ts=1695599985909&to_ts=1698191985909&live=true), but I'm only seeing data from Oct 9 2023 onwards. Not sure why older data isn't showing up here

Anyways, I see a number of visits to /Tools/Sale still, though it's pretty low relatively speaking.

![image](https://github.com/iFixit/react-commerce/assets/52104630/50a17b0a-23c8-4d1b-bbab-efd9c6d09c82)

**Comment by sterlinghirsh** [comment] 2023-10-25 06:27
10 a day is enough to keep it the redirect.

**Comment by dhmacs** [comment] 2023-10-25 08:22
A way to phase this out while preventing new wrong url would be to maintain a list of the wrong url and only redirect those until they have traffic. What do you think @sterlinghirsh ?

PS: Can we tell if the traffic comes from real users vs bot/crawlers ?

**Comment by sterlinghirsh** [comment] 2023-10-25 16:51
I'm just going to close this since I don't really care about doing the vice-versa anymore.

**Comment by dhmacs** [comment] 2023-10-25 16:51
The problem is that we're still supporting marketing product lists under tools paths. If you think it's not worth addressing than should we close this issue?

**Closed by sterlinghirsh** 2023-10-25 16:51 UTC
Labels: 0 bug

**Comment by masonmcelvain** [comment] 2023-10-25 17:15
> Can we tell if the traffic comes from real users vs bot/crawlers/iFixit employees visiting the page ?

We have the user agent in the logs, but I don't see any other identifying information.

![image](https://github.com/iFixit/react-commerce/assets/52104630/1eeecab0-47a6-4b4b-a700-8d14fc1cd8b2)
[link](https://app.datadoghq.com/logs?query=service%3Areact-commerce-prod.vercel.app%20%40path%3A%22en-US%2FTools%2F%5Bhandle%5D%22%20%40statusCode%3A308%20%40proxy.path%3A%5C%2FTools%5C%2FSale%2A%20&agg_q=%40proxy.userAgent&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&view=spans&viz=timeseries&from_ts=1695599985909&to_ts=1698191985909&live=true)
