### ISSUE TITLE
Troubleshooting: Device card on mobile formatting issue

### ISSUE THREAD

**Issue by kthaler** [iFixit/react-commerce#2044] opened 2023-10-20 22:16 UTC
When in mobile view, the device card in Troubleshooting pages has some formatting issues. Examples:

https://react-commerce-git-troubleshooting-fix-relatedpro-a72337-ifixit.vercel.app/Troubleshooting/iPhone_11/Will+Not+Turn+On/478192
![Screenshot 2023-10-20 at 3 08 24 PM](https://github.com/iFixit/react-commerce/assets/145375039/bdfd5579-6700-4c35-a48c-93322f4c9b9b)

https://react-commerce-git-troubleshooting-fix-relatedpro-a72337-ifixit.vercel.app/Troubleshooting/Dryer/Smells+Like+Gas/479708
![Screenshot 2023-10-20 at 3 10 59 PM](https://github.com/iFixit/react-commerce/assets/145375039/97fd968e-9062-4d1b-9f01-1f6b921509dc)

Related Comment: https://github.com/iFixit/react-commerce/pull/2039#issuecomment-1773415272

**Comment by sctice-ifixit** [comment] 2023-10-20 22:20
Duplicate of https://github.com/iFixit/ifixit/issues/50335.

**Closed by sctice-ifixit** 2023-10-20 22:20 UTC
