### ISSUE TITLE
Item Type filtering is very laggy

### ISSUE THREAD

**Issue by deltuh-vee** [iFixit/react-commerce#1004] opened 2022-11-08 21:05 UTC
## Description
Filtering by Item Type has considerable lag. Based off of the console errors, there might be a memory leak somewhere.
![CleanShot 2022-11-08 at 12 44 59](https://user-images.githubusercontent.com/5289715/200674962-730e3ab6-847b-41b8-b444-31cce3306ac5.png)

## Steps to reproduce
1. Visit https://www.ifixit.com/Parts
2. Filter by Accessories under Item Type

https://user-images.githubusercontent.com/5289715/200674862-a59ac9f5-20dc-4e1a-aaca-7e613295f843.mp4

**Comment by dhmacs** [comment] 2022-11-08 22:45
I'm running on a similar issue in my React 18 branch, that seems to be caused by `useInstantSearch` in `RefinementSingleSelect` component. I'm working on a refactor that doesn't use `useInstantSearch`.
The two issues might be related, although I'm not experiencing the same lag as seen in the screencast.

cc @danielbeardsley

**Comment by danielbeardsley** [comment] 2022-11-08 22:47
This seems like something probably recent and we could probably git-bisect it pretty quick.

**Comment by danielbeardsley** [comment] 2022-11-09 19:56
Tried bisecting, but it was still bad going back a month and a half.

**Comment by dhmacs** [comment] 2022-11-09 20:23
I think I'm close to a solution for the memory leak issue, just need a little bit more refactoring.. I'll keep working on it after dinner. 
Should I assign this to myself, since probably the work that I'm doing will fix this too?

cc @danielbeardsley

**Comment by danielbeardsley** [comment] 2022-11-09 20:56
> I'll keep working on it after dinner.
> Should I assign this to myself, since probably the work that I'm doing will fix this too?

:+1:

**Closed** 2022-11-14 18:03 UTC
