### ISSUE TITLE
Add manage link to user menu (Admins only)

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#152] opened 2021-12-10 19:07 UTC
Current react-commerce user menu:
![image](https://user-images.githubusercontent.com/589425/216170610-8d421822-a08f-4c50-bbd6-e5065b13c89f.png)

Current iFixit main user menu:
![image](https://user-images.githubusercontent.com/589425/216170740-4f7769f4-7ff1-4ea1-a1b4-a642c99aac95.png)

The main differences here are the "My Team" and "Manage" links.

For "My Team", if the user api responds with a non-empty teams array, add the My Team link to `/Team`. This will redirect to the correct team and doesn't require generating a custom link. 
![image](https://user-images.githubusercontent.com/589425/216171560-0188a841-19f0-4b33-947a-67d1a0ad0780.png)

For "Manage", if the user api responds with a field "links" that contains a key "manage", include a link to `/Manage`. That target url is the value of user.links.manage.
 
![image](https://user-images.githubusercontent.com/589425/216171781-e1afca0e-63ae-4000-b80e-6d93a0ba0c43.png)

For the moment, we won't try to handle anything else in the "links" object.

**Comment by sterlinghirsh** [comment] 2023-02-02 18:10
This is similar to / duplicate of #256

**Comment by sterlinghirsh** [comment] 2023-02-04 02:12
I closed #256 in favor of this. As @masonmcelvain mentioned in that issue, `links` is now `{}` when empty instead of `[]`.

**Comment by federicobadini** [comment] 2023-02-06 10:18
Is it possible to have a user with sufficient permissions to see those management links?

**Comment by sterlinghirsh** [comment] 2023-02-07 01:47
I made your user an admin on cominor. You may have to log out/in to see the change.

**Closed** 2023-05-04 21:13 UTC
Labels: 0 feature
