### ISSUE TITLE
Add Notify Me component

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#688] opened 2022-09-08 16:23 UTC
API: https://www.ifixit.com/api/2.0/doc/Cart#adds-a-specified-email-to-a-mailing-list
- We will add an updated api endpoint for this to rely on shop domain and sku: https://github.com/iFixit/ifixit/issues/44578
Example implementation: https://github.com/iFixit/ifixit/blob/master/product-page-components/src/lib/notify_product/notify_product.js

**Comment by dhmacs** [comment] 2022-09-12 16:03
@sterlinghirsh I see that the API requires a sales id and it is pretty much hard coded to `1` everywhere it's being used:

https://github.com/iFixit/ifixit/blob/31aea6390a2e537b25722a3aa44f3425bb210c30/carpenter-frontend/Cart/FeaturedProduct/Components/hero_purchase.js#L49
<img width="687" alt="image" src="https://user-images.githubusercontent.com/4640135/189701075-c79f2ae5-c1aa-4ce9-a087-749ac56e2ac7.png">

Should I hard code it too? Or should this be put into the store model on Strapi as a configurable param?

**Comment by dhmacs** [comment] 2022-09-19 15:21
@masonmcelvain is this supposed to work now? I've seen a couple of PR have been merged, but I've just tried and I'm still getting CORS error.

**Comment by masonmcelvain** [comment] 2022-09-19 17:02
@danielbeardsley I'm also reproducing the CORS errors still. We expected https://github.com/iFixit/ifixit/pull/44668 to fix this, right? Let's take another look.

**Comment by danielbeardsley** [comment] 2022-09-19 22:29
Can someone be a little more explicit with the reproduction steps? I'm seeing this endpoint succeed when I'm running locally and using `www.cominor.com` as the `IFIXIT_ORIGIN`:

![image](https://user-images.githubusercontent.com/26855/191130629-dc24d0aa-8e79-4759-acf6-95ccec5dacda.png)

**Comment by danielbeardsley** [comment] 2022-09-19 22:32
And also succeed against `www.ifixit.com`:
![image](https://user-images.githubusercontent.com/26855/191130965-298a1faf-bed6-4d1b-a28e-457bcf5ebd88.png)

**Comment by dhmacs** [comment] 2022-09-20 06:04
## Repro steps

1. Check out branch `use-new-back-in-stock-api`
2. Install dependencies and run the dev server
3. Visit http://localhost:3000/Products/17-blade-5-pcs
4. Submit your email via the notify me form

As of today, I'm getting this error when I do so:

<img width="1212" alt="Screenshot 2022-09-20 at 08 02 03" src="https://user-images.githubusercontent.com/4640135/191179112-bf50ebec-b147-4e8a-b537-b886cb957653.png">

cc @danielbeardsley

**Comment by masonmcelvain** [comment] 2022-09-20 16:34
> Can someone be a little more explicit with the reproduction steps? I'm seeing this endpoint succeed when I'm running locally and using `www.cominor.com` as the `IFIXIT_ORIGIN`:
> 
> ![image](https://user-images.githubusercontent.com/26855/191130629-dc24d0aa-8e79-4759-acf6-95ccec5dacda.png)

FWIW, the endpoint we're interested in is `notifyWhenSkuInStock`, not `notifyWhenInStock`. Not sure if that's the reason we're seeing different results though.

**Comment by danielbeardsley** [comment] 2022-09-20 18:15
> FWIW, the endpoint we're interested in is `notifyWhenSkuInStock`, not `notifyWhenInStock`. Not sure if that's the reason we're seeing different results though.

I'm not seeing where we talk to that API? ...   OH! You're talking about code on a different branch. 
![image](https://user-images.githubusercontent.com/26855/191324524-4d4b6f60-463f-49d7-a8c7-30ffd2d73c5d.png)

We haven't yet included that new API in some CORS exemptions. I think every time I've looked, I didn't realize this was a new API with a *very* similar name to the old one and mistook the exemptions for the old API.

I'll fix this and possible broaden the exemptions.

**Comment by dhmacs** [comment] 2022-09-30 16:53
Just so we're all on the same page, we still have a CORS error

cc @sterlinghirsh @danielbeardsley @masonmcelvain

**Comment by danielbeardsley** [comment] 2022-10-03 18:50
FYI, I just pushed a commit to that branch to *stop* sending credentials cause they aren't needed. We'll address the CORS problem separately with https://github.com/iFixit/ifixit/issues/44880

**Closed** 2022-10-04 17:14 UTC
Labels: 0 feature, needs_more_spec
